// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7H5hIowWvcGmIq7m2RofB843-Eyfz1g',
    appId: '1:861858508386:web:581b65d5cae86b1c692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    authDomain: 'cordrila.firebaseapp.com',
    storageBucket: 'cordrila.appspot.com',
    measurementId: 'G-W0Z4TF36Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4tJRzflin1O6UMabgoXdhEzf4WhAkHCo',
    appId: '1:861858508386:android:91ff45b105819458692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    storageBucket: 'cordrila.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQthrt9SEnKt3r37zQz8tM0_LHfxrkyM',
    appId: '1:861858508386:ios:35492fb99eeaaf58692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    storageBucket: 'cordrila.appspot.com',
    iosBundleId: 'com.example.cordrilaSysytems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQthrt9SEnKt3r37zQz8tM0_LHfxrkyM',
    appId: '1:861858508386:ios:35492fb99eeaaf58692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    storageBucket: 'cordrila.appspot.com',
    iosBundleId: 'com.example.cordrilaSysytems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq7H5hIowWvcGmIq7m2RofB843-Eyfz1g',
    appId: '1:861858508386:web:22dd1fc78ba3466b692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    authDomain: 'cordrila.firebaseapp.com',
    storageBucket: 'cordrila.appspot.com',
    measurementId: 'G-MZLZL86DP6',
  );
}
